# .pre-commit-config.yaml

repos:
  - repo: https://github.com/ibm/detect-secrets
    rev: 0.13.1+ibm.61.dss
    hooks:
      - id: detect-secrets
        args:
          - --baseline
          - .secrets.baseline
          - --use-all-plugins
          - --fail-on-unaudited
        files: ^(?!.*(package-lock\.json|\.io$|venv/lib/python3.12/site-packages)).*$


  - repo: local
    hooks:
      - id: validate-agent
        name: Run validate_agent.py
        entry: python validate_agent.py
        language: python
        types: [python]
        additional_dependencies: [pyyaml]
        always_run: true
        pass_filenames: false
        files: ^(?!.*validation_report\.json).*$
