name: Test CI/CD

on:
  push:
    branches:
      - main

jobs:
  backend-test:
    runs-on: ubuntu-latest
    name: Build & Test Backend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install backend dependencies
        run: |
          cd backend
          pip install -r requirements.txt
      - name: Run backend test (curl check)
        run: |
          nohup python3 backend/app.py > log.txt 2>&1 &
          sleep 5
          curl --fail http://localhost:5000/ || (echo "Log output:" && cat log.txt && exit 1)


  frontend-test:
    runs-on: ubuntu-latest
    name: Build Frontend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install frontend dependencies and build
        run: |
          cd frontend
          npm install
          npm run build
